(****************************************************************
 * Identifiers of builtin function, types, etc.
 *
 * Copyright (C) 2022-2024 Intel Corporation
 * SPDX-Licence-Identifier: BSD-3-Clause
 ****************************************************************)

(* Functions *)
let not_bool          = Ident.mk_fident "not_bool"
let neg_int           = Ident.mk_fident "neg_int"
let not_bits          = Ident.mk_fident "not_bits"
let zeros_bits        = Ident.mk_fident "zeros_bits"
let ones_bits         = Ident.mk_fident "ones_bits"
let and_bool          = Ident.mk_fident "and_bool"
let or_bool           = Ident.mk_fident "or_bool"
let implies_bool      = Ident.mk_fident "implies_bool"
let eq_enum           = Ident.mk_fident "eq_enum"
let eq_int            = Ident.mk_fident "eq_int"
let le_int            = Ident.mk_fident "le_int"
let add_int           = Ident.mk_fident "add_int"
let sub_int           = Ident.mk_fident "sub_int"
let mul_int           = Ident.mk_fident "mul_int"
let eq_bits           = Ident.mk_fident "eq_bits"
let add_bits          = Ident.mk_fident "add_bits"
let sub_bits          = Ident.mk_fident "sub_bits"
let mul_bits          = Ident.mk_fident "mul_bits"
let in_mask           = Ident.mk_fident "in_mask"
let and_bits          = Ident.mk_fident "and_bits"
let or_bits           = Ident.mk_fident "or_bits"
let lsr_bits          = Ident.mk_fident "lsr_bits"
let lsl_bits          = Ident.mk_fident "lsl_bits"
let max               = Ident.mk_fident "Max"
let min               = Ident.mk_fident "Min"
let eq_bool           = Ident.mk_fident "eq_bool"
let equiv_bool        = Ident.mk_fident "equiv_bool"
let ne_bool           = Ident.mk_fident "ne_bool"
let ne_enum           = Ident.mk_fident "ne_enum"
let align_int         = Ident.mk_fident "align_int"
let exact_div_int     = Ident.mk_fident "exact_div_int"
let fdiv_int          = Ident.mk_fident "fdiv_int"
let frem_int          = Ident.mk_fident "frem_int"
let ge_int            = Ident.mk_fident "ge_int"
let gt_int            = Ident.mk_fident "gt_int"
let is_pow2_int       = Ident.mk_fident "is_pow2_int"
let lt_int            = Ident.mk_fident "lt_int"
let mod_pow2_int      = Ident.mk_fident "mod_pow2_int"
let ne_int            = Ident.mk_fident "ne_int"
let pow2_int          = Ident.mk_fident "pow2_int"
let pow_int_int       = Ident.mk_fident "pow_int_int"
let shl_int           = Ident.mk_fident "shl_int"
let shr_int           = Ident.mk_fident "shr_int"
let zdiv_int          = Ident.mk_fident "zdiv_int"
let zrem_int          = Ident.mk_fident "zrem_int"
let add_real          = Ident.mk_fident "add_real"
let cvt_int_real      = Ident.mk_fident "cvt_int_real"
let divide_real       = Ident.mk_fident "divide_real"
let eq_real           = Ident.mk_fident "eq_real"
let ge_real           = Ident.mk_fident "ge_real"
let gt_real           = Ident.mk_fident "gt_real"
let le_real           = Ident.mk_fident "le_real"
let lt_real           = Ident.mk_fident "lt_real"
let mul_real          = Ident.mk_fident "mul_real"
let ne_real           = Ident.mk_fident "ne_real"
let neg_real          = Ident.mk_fident "neg_real"
let pow2_real         = Ident.mk_fident "pow2_real"
let round_down_real   = Ident.mk_fident "round_down_real"
let round_tozero_real = Ident.mk_fident "round_tozero_real"
let round_up_real     = Ident.mk_fident "round_up_real"
let sqrt_real         = Ident.mk_fident "sqrt_real"
let sub_real          = Ident.mk_fident "sub_real"
let cvt_bits_sint     = Ident.mk_fident "cvt_bits_sint"
let cvt_bits_uint     = Ident.mk_fident "cvt_bits_uint"
let cvt_int_bits      = Ident.mk_fident "cvt_int_bits"
let eor_bits          = Ident.mk_fident "eor_bits"
let frem_bits_int     = Ident.mk_fident "frem_bits_int"
let notin_mask        = Ident.mk_fident "notin_mask"
let asr_bits          = Ident.mk_fident "asr_bits"
let ne_bits           = Ident.mk_fident "ne_bits"
let replicate_bits    = Ident.mk_fident "replicate_bits"
let append_str_str    = Ident.mk_fident "append_str_str"
let cvt_bits_str      = Ident.mk_fident "cvt_bits_str"
let cvt_bool_str      = Ident.mk_fident "cvt_bool_str"
let cvt_int_decstr    = Ident.mk_fident "cvt_int_decstr"
let cvt_int_hexstr    = Ident.mk_fident "cvt_int_hexstr"
let cvt_real_str      = Ident.mk_fident "cvt_real_str"
let eq_str            = Ident.mk_fident "eq_str"
let ne_str            = Ident.mk_fident "ne_str"
let print_int_hex     = Ident.mk_fident "print_int_hex"
let print_int_dec     = Ident.mk_fident "print_int_dec"
let print_char        = Ident.mk_fident "print_char"
let print_str         = Ident.mk_fident "print_str"
let print_bits_hex    = Ident.mk_fident "print_bits_hex"
let print_bits        = Ident.mk_fident "print_bits"
let ram_init          = Ident.mk_fident "ram_init"
let ram_read          = Ident.mk_fident "ram_read"
let ram_write         = Ident.mk_fident "ram_write"
let add_bits_int      = Ident.mk_fident "add_bits_int"
let sub_bits_int      = Ident.mk_fident "sub_bits_int"
let mul_bits_int      = Ident.mk_fident "mul_bits_int"
let zero_extend_bits  = Ident.mk_fident "zero_extend_bits"
let append_bits       = Ident.mk_fident "append_bits"
let mk_mask           = Ident.mk_fident "mk_mask"
let mask_int          = Ident.mk_fident "mask_int"
let zero_extend       = Ident.mk_fident "ZeroExtend"
let ones              = Ident.mk_fident "Ones"
let zeros             = Ident.mk_fident "Zeros"
let is_ones           = Ident.mk_fident "IsOnes"
let is_zero           = Ident.mk_fident "IsZero"

let take_cold_reset     = Ident.mk_fident "__TakeColdReset"
let instruction_execute = Ident.mk_fident "__InstructionExecute"
let get_pc              = Ident.mk_fident "__getPC"
let set_pc              = Ident.mk_fident "__setPC"
let elf_write_memory    = Ident.mk_fident "__ELFWriteMemory"
let elf_write_memory32  = Ident.mk_fident "__ELFWriteMemory32"

let asl_fake_return_value    = Ident.mk_ident "ASL_fake_return_value"
let asl_error_unmatched_case = Ident.mk_fident "ASL_error_unmatched_case"
let asl_extract_bits         = Ident.mk_fident "asl_extract_bits"
let asl_extract_int          = Ident.mk_fident "asl_extract_int"
let asl_file_open            = Ident.mk_fident "asl_file_open"
let asl_file_write           = Ident.mk_fident "asl_file_write"
let asl_file_getc            = Ident.mk_fident "asl_file_getc"
let asl_fuzz                 = Ident.mk_fident "ASL_fuzz"

let trace_next            = Ident.mk_fident "__TraceNext"
let trace_physical_memory = Ident.mk_fident "__TracePhysicalMemory"
let trace_virtual_memory  = Ident.mk_fident "__TraceVirtualMemory"
let trace_page_table_walk = Ident.mk_fident "__TracePageTableWalk"
let trace_error           = Ident.mk_fident "__TraceError"
let trace_event           = Ident.mk_fident "__TraceEvent"

(* Other identifiers *)
let boolean_ident   = Ident.mk_ident "boolean"
let integer_ident   = Ident.mk_ident "integer"
let string_ident    = Ident.mk_ident "string"
let real_ident      = Ident.mk_ident "real"
let bits_ident      = Ident.mk_ident "bits"
let wildcard_ident  = Ident.mk_ident "_"
let dash_ident      = Ident.mk_ident "-"
let mask_ident      = Ident.mk_ident "__mask"
let exception_ident = Ident.mk_ident "__Exception"
let asl_integer     = Ident.mk_ident "asl_integer"
let ram             = Ident.mk_ident "__RAM"
let true_ident      = Ident.mk_ident "TRUE"
let false_ident     = Ident.mk_ident "FALSE"

(****************************************************************
 * End
 ****************************************************************)
