(** Identifiers used for variable names, function names, etc.

    There are two kinds of identifier:
    - Ident is generated by the parser - it is just a string
    - FIdent is generated by the disambiguation part of the typechecker and
      includes a unique label to distinguish different entities with
      the same name in the source syntax.
 *)

type t =
    | Ident of string
    | FIdent of string * int

val pprint : t -> string

val name_of_FIdent : t -> string

val add_tag : t -> tag:int -> t

val add_prefix : t -> prefix:string -> t

val add_suffix : t -> suffix:string -> t

val compare : t -> t -> int

val matches : t -> name:string -> bool

val is_function : t -> bool
