name: McAfee Virus Scan
on:
  workflow_dispatch:

permissions: read-all

jobs:
  virus:
    name: McAfee Virus Scan
    runs-on: [self-hosted, Linux, ubuntu-latest]
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Execute Scan
        uses: intel-innersource/frameworks.devops.github.actions.mcafee@main

